// <auto-generated />
namespace PropertyManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetDateCompletedtomirrorDateSubmittedinservicerequests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetDateCompletedtomirrorDateSubmittedinservicerequests));
        
        string IMigrationMetadata.Id
        {
            get { return "201711071441251_Set DateCompleted to mirror DateSubmitted in servicerequests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
