// <auto-generated />
namespace PropertyManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Resetdatesubmittedtooriginalinservicerequests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resetdatesubmittedtooriginalinservicerequests));
        
        string IMigrationMetadata.Id
        {
            get { return "201711071413267_Reset datesubmitted to original in servicerequests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
